import SwiftUI

@main
struct ClaudeUsageApp: App {
    @NSApplicationDelegateAdaptor(AppDelegate.self) private var appDelegate

    var body: some Scene {
        WindowGroup("Claude Usage") {
            ContentView()
        }
        .windowResizability(.contentSize)

        Window("Claude Usage — History", id: "history") {
            HistoryView()
        }
        .defaultSize(width: 900, height: 820)
    }
}

/// Running as a SwiftUI SPM executable, the process defaults to a background
/// activation policy; promote it so the window shows and takes focus.
final class AppDelegate: NSObject, NSApplicationDelegate {
    func applicationDidFinishLaunching(_ notification: Notification) {
        NSApplication.shared.setActivationPolicy(.regular)
        NSApplication.shared.activate(ignoringOtherApps: true)

        // An SPM executable has no bundle to read CFBundleIconName from, so set
        // the Dock icon by hand. Generated by scripts/build-icons.sh.
        if let url = Bundle.module.url(forResource: "ClaudeUsage", withExtension: "icns"),
           let icon = NSImage(contentsOf: url) {
            NSApplication.shared.applicationIconImage = icon
        }
    }

    func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
        true
    }
}
